In [2]:
import xarray as xr
import sys
sys.path.append('/glade/u/home/adamhb/Earth-System-Model-Tools')
import esm_tools
import importlib
importlib.reload(esm_tools)
import numpy as np
import pandas as pd

In [2]:
fields = ['FATES_SEED_PROD_USTORY_SZ','FATES_VEGC_AP','FATES_BURNFRAC',
              'FATES_NPLANT_PF','FATES_NPLANT_SZPF','FATES_NPLANT_RESPROUT_PF',
              'FATES_FIRE_INTENSITY_BURNFRAC','FATES_IGNITIONS',
              'FATES_MORTALITY_FIRE_SZPF','FATES_BASALAREA_SZPF','FATES_CANOPYCROWNAREA_APPF',
              'FATES_CANOPYCROWNAREA_PF','FATES_CROWNAREA_PF',
              'FATES_CROWNAREA_APPF','FATES_FUEL_AMOUNT_APFC','FATES_NPLANT_SZPF','FATES_FUEL_AMOUNT_APFC',
              'FATES_PATCHAREA_AP','FATES_CROWNAREA_PF','FATES_VEGC_ABOVEGROUND','FATES_NPP_PF']

In [4]:
old = pd.read_csv('/glade/work/adamhb/processed_output/CZ2_equilibrium_011824_-17e2acb6a_FATES-5b076b69/CZ2-PEAS_passing_no_fire_011924.csv')

In [7]:
old[['inst','AGB','TreeStemD','BA']]

inst        AGB   TreeStemD         BA
0      1   4.775533  308.425725  21.981668
1      2   3.554558  143.966824  10.706932
2      3   2.776733  255.824700  13.007200
3      4   2.625335  154.704973   6.733777
4      5   4.115454  291.985646  14.177242
5      8   5.611041  234.635584  23.465542
6      9   5.455863  181.077160  15.421281
7     13   2.415682   41.951537   3.253844
8     14  10.026567  203.356054  44.556767
9     15   3.799206  295.176804   9.942947
10    17   6.564092  271.406658  22.175463
11    21   6.132103  192.648564  22.010650
12    22   8.277864  415.440053  33.961685
13    23  11.586305  300.594158  33.968853
14    24   2.890581  262.553655   8.391390
15    25   7.262706  396.627113  23.185898
16    26   3.979721  314.842127  22.064580
17    27   5.221775  549.660213  23.114182
18    29   4.872829  627.268478  21.625484
19    30   3.423601  104.932822  10.060970
20    31   5.477417  360.213630  21.772188
21    33  11.327408  287.000202  27.570990
22    37   6.317751  426.837131  21.618208
23    38   5.764065  802.651495  25.194845
24    41   8.037908  161.729120  19.452946
25    42   7.279378  433.390625  26.073187
26    45   6.994952  517.186970  17.561577
27    46   4.026773   95.118405  10.162040
28    48   4.889343  290.010870  15.914538
29    50   4.556526  238.555763  14.099928
30    51  20.895950  201.623961  62.870370
31    52   3.979721  314.842127  22.064580
32    53   7.241310  255.586244  25.699512

In [9]:
new = pd.read_csv('/glade/work/adamhb/processed_output/CZ2_equilibrium_011824_-17e2acb6a_FATES-5b076b69/eq_1864_1870_metrics_test.csv')
new[['inst_tag','AGB','TreeStemD','BA']]

inst_tag        AGB   TreeStemD         BA
0          1   4.775521  315.015055  21.711960
1          2   3.550185  149.413012  10.643923
2          3   2.801875  270.160846  12.686672
3          4   2.645134  129.464567   6.695764
4          5   4.143051  288.847908  14.218716
5          8   5.625971  239.579938  23.161537
6          9   5.513327  179.237016  15.568836
7         13   2.457472   43.553114   3.252878
8         14  10.010455  207.074173  44.678116
9         15   3.783551  296.892002  10.212789
10        17   6.558630  277.764648  22.063967
11        21   6.119179  201.944485  21.854465
12        22   8.323569  428.410396  33.963474
13        23  11.592097  299.023204  34.094760
14        24   2.847686  246.501323   8.308785
15        25   7.263680  395.101085  23.213556
16        26   3.914041  294.330828  22.018890
17        27   5.098082  527.812615  22.513367
18        29   4.882263  608.858988  21.413036
19        30   3.463063  105.875507  10.369763
20        31   5.442259  370.251201  21.523985
21        33  11.369958  262.425467  27.731363
22        37   6.310484  381.701700  21.544247
23        38   5.764205  820.975825  25.200745
24        41   8.010354  164.547823  19.521597
25        42   7.226892  455.881022  25.954578
26        45   7.011674  524.025708  17.523932
27        46   3.996258   96.086487  10.169642
28        48   4.850025  296.270251  15.926610
29        50   4.574982  249.386728  14.243633
30        51  20.917992  204.821192  63.072250
31        52   3.914041  294.330828  22.018890
32        53   7.356057  248.333327  26.425863

In [3]:
p = '/glade/derecho/scratch/adamhb/CZ2_trans_1951_2020_012824_-17e2acb6a_FATES-5b076b69/lnd/hist'

full_paths = esm_tools.filter_output_files(p,'0001',1960,1980)

ds = esm_tools.multiple_netcdf_to_xarray(full_paths, fields)

In [37]:
esm_tools.get_PHS_FLI_thresh(ds,1200)

60.526315789473685

In [35]:
esm_tools.get_PHS_FLI_thresh2(ds,1200)

60.526315789473685

In [43]:
pd.read_csv('/glade/work/adamhb/processed_output/test.csv')

Unnamed: 0         BA   BA_pine   BA_cedar    BA_fir  BA_shrub  \
inst_tag                                                                   
1                  0  53.240734  2.410488  45.811474  1.809816  0.110077   
2                  1  26.445103  1.944527   7.340004  0.504479  0.233824   
3                  2  43.694252  4.342852  24.116556  2.920357  0.248402   

             BA_oak        AGB   TreeStemD  TreeStemD_40  ...  \
inst_tag                                                  ...   
1          3.208953  14.534731  344.853327    172.704607  ...   
2         16.656092  10.277606  209.724382     65.938574  ...   
3         12.314486  14.178148  303.588565    127.781611  ...   

          ResproutD_shrub  ShannonE       NPP  FailedPFTs  \
inst_tag                                                    
1                     0.0  0.352527  0.981594           0   
2                     0.0  0.594369  1.024098           0   
3                     0.0  0.698346  0.960416           0   

          Pct_shrub_cover_canopy  Pct_shrub_cover  Combustible_fuel  \
inst_tag                                                              
1                       0.000014         0.010859          0.632735   
2                       0.008797         0.018847          0.836894   
3                       0.005971         0.022764          0.881884   

          Burned_area  Pct_high_severity_1700  Pct_high_severity_3500  
inst_tag                                                               
1               0.000                     0.0                     0.0  
2               0.005                    50.0                     0.0  
3               0.003                    40.0                     0.0  

[3 rows x 24 columns]

In [21]:
esm_tools.get_awfi(ds).values

/glade/work/adamhb/opt/miniconda/envs/env4/lib/python3.8/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))


array([          nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan, 1215.92689263,
       1333.51489835, 1249.1682744 , 1249.58058579,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan, 1282.47315573,
       1151.18326872,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan, 1075.94957932,
       1474.56816155, 1165.12861454,           nan,           

In [24]:
def get_awfi(ds):
    '''
    Returns area-weighted fire intensity (kW m-1)
    '''
    a1 = ds.FATES_FIRE_INTENSITY_BURNFRAC.values
    a2 = (ds.FATES_BURNFRAC.values * s_per_day)

    aw_fi = np.divide(a1, a2, out=np.zeros_like(a1), where=a2 != 0)

    return aw_fi / 1000

In [26]:
awfi = get_awfi(ds)

In [28]:
np.count_nonzero(awfi)

38

In [14]:
s_per_day = 86400

In [17]:
a = [1,3,4,5,0,0,3]
b = [1,2,0,4,2,0,4]
np.divide(a,b,where )

/glade/derecho/scratch/adamhb/tmp/ipykernel_26397/3645307168.py:3: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)
/glade/derecho/scratch/adamhb/tmp/ipykernel_26397/3645307168.py:3: RuntimeWarning: invalid value encountered in divide
  np.divide(a,b)


array([1.  , 1.5 ,  inf, 1.25, 0.  ,  nan, 0.75])

In [15]:
awfi = np.divide(ds.FATES_FIRE_INTENSITY_BURNFRAC, ds.FATES_BURNFRAC * s_per_day, out=np.zeros_like(ds.FATES_FIRE_INTENSITY_BURNFRAC), where=(ds.FATES_BURNFRAC * s_per_day) != 0) / 1000

NotImplementedError: The out parameter is not fully supported. Received type ndarray, expected Dask Array

In [9]:
ds.FATES_FIRE_INTENSITY_BURNFRAC.values

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5481700e-01,
       1.7748593e+00, 5.0118843e+01, 3.3485188e+01, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.4101060e-01,
       7.7384782e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.7680965e-02,
       6.1264610e-01, 2.8110912e+01, 0.0000000e+00, 0.0000000e